<a href="https://colab.research.google.com/github/SamyarZamani/Persian-Sentiment-Analysis/blob/main/HP_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# importing part

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("housePrice.csv")

Saving housePrice.csv to housePrice (1).csv


# data info part

In [ ]:
df.head()

Area  Room  Parking  Warehouse  Elevator         Address         Price  \
0   63     1     True       True      True         Shahran  1.850000e+09   
1   60     1     True       True      True         Shahran  1.850000e+09   
2   79     2     True       True      True          Pardis  5.500000e+08   
3   95     2     True       True      True   Shahrake Qods  9.025000e+08   
4  123     2     True       True      True  Shahrake Gharb  7.000000e+09   

   Price(USD)  
0    61666.67  
1    61666.67  
2    18333.33  
3    30083.33  
4   233333.33

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3479 entries, 0 to 3478
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Area        3479 non-null   object 
 1   Room        3479 non-null   int64  
 2   Parking     3479 non-null   bool   
 3   Warehouse   3479 non-null   bool   
 4   Elevator    3479 non-null   bool   
 5   Address     3456 non-null   object 
 6   Price       3479 non-null   float64
 7   Price(USD)  3479 non-null   float64
dtypes: bool(3), float64(2), int64(1), object(2)
memory usage: 146.2+ KB


In [ ]:
df.isna().sum()

Area           0
Room           0
Parking        0
Warehouse      0
Elevator       0
Address       23
Price          0
Price(USD)     0
dtype: int64

# preprocessing part

In [ ]:
df['Address'] = df['Address'].fillna("Unknown")
import numpy as np
from sklearn.preprocessing import  LabelEncoder
le = LabelEncoder()
df['Address'] = le.fit_transform(df['Address'])

print(df['Address'])
print('''

''')
print(df['Address'].isnull().sum())

0       156
1       156
2       117
3       152
4       150
       ... 
3474    163
3475    105
3476    115
3477     39
3478    115
Name: Address, Length: 3479, dtype: int64



0


In [ ]:
df['Area'] = pd.to_numeric(df['Area'], errors='coerce')
print('befor')
print(df['Area'].isnull().sum())
print('''
''')
df = df.dropna(subset=['Area'])
print(df['Area'].dtype)
print('''
''')
print('after')
print(df['Area'].isnull().sum())

befor
6


float64


after
0


In [ ]:
bool_columns = ['Parking', 'Warehouse', 'Elevator']
df[bool_columns] = df[bool_columns].astype(int)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3473 entries, 0 to 3478
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Area        3473 non-null   float64
 1   Room        3473 non-null   int64  
 2   Parking     3473 non-null   int64  
 3   Warehouse   3473 non-null   int64  
 4   Elevator    3473 non-null   int64  
 5   Address     3473 non-null   int64  
 6   Price       3473 non-null   float64
 7   Price(USD)  3473 non-null   float64
dtypes: float64(3), int64(5)
memory usage: 244.2 KB


In [ ]:
x = df.drop(columns=['Price', 'Price(USD)'])
y_price_rial = df['Price']
y_price_usd = df['Price(USD)']
print(x.head())
print('''

''')
print(y_price_rial.head())
print('''

''')
print(y_price_usd.head())

    Area  Room  Parking  Warehouse  Elevator  Address
0   63.0     1        1          1         1      156
1   60.0     1        1          1         1      156
2   79.0     2        1          1         1      117
3   95.0     2        1          1         1      152
4  123.0     2        1          1         1      150



0    1.850000e+09
1    1.850000e+09
2    5.500000e+08
3    9.025000e+08
4    7.000000e+09
Name: Price, dtype: float64



0     61666.67
1     61666.67
2     18333.33
3     30083.33
4    233333.33
Name: Price(USD), dtype: float64


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)
print(x)

[[-0.63116113 -1.42325455  0.42342287  0.30523705  0.5194569   0.99755258]
 [-0.67441648 -1.42325455  0.42342287  0.30523705  0.5194569   0.99755258]
 [-0.40046592 -0.10513107  0.42342287  0.30523705  0.5194569   0.22659179]
 ...
 [-0.45813973 -0.10513107 -2.36170521 -3.27614226 -1.92508755  0.18705534]
 [-0.02558621 -0.10513107  0.42342287  0.30523705  0.5194569  -1.31532979]
 [-0.35721057 -0.10513107 -2.36170521  0.30523705  0.5194569   0.18705534]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train_rial, X_test_rial, y_train_rial, y_test_rial = train_test_split(x, y_price_rial, test_size=0.2, random_state=42)
X_train_usd, X_test_usd, y_train_usd, y_test_usd = train_test_split(x, y_price_usd, test_size=0.2, random_state=42)

# trainig part

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

model_rial = RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    random_state=42
)
model_rial.fit(X_train_rial, y_train_rial)

y_pred_rial = model_rial.predict(X_test_rial)
mse_rial = mean_squared_error(y_test_rial, y_pred_rial)
r2_rial = r2_score(y_test_rial, y_pred_rial)

print("(Rial) price =")
print(f"MSE: {mse_rial:,.0f}")
print(f"RMSE: {mse_rial**0.5:,.0f}")
print(f"R² Score: {r2_rial:.3f}")

(Rial) price =
MSE: 15,075,203,087,057,416,192
RMSE: 3,882,679,885
R² Score: 0.780


In [ ]:
model_usd = RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    random_state=42
)
model_usd.fit(X_train_usd, y_train_usd)
y_pred_usd = model_usd.predict(X_test_usd)

mse_usd = mean_squared_error(y_test_usd, y_pred_usd)
r2_usd = r2_score(y_test_usd, y_pred_usd)

print("(USD) price =")
print(f"MSE: {mse_usd:,.0f}")
print(f"RMSE: {mse_usd**0.5:,.0f}")
print(f"R² Score: {r2_usd:.3f}")

(USD) price =
MSE: 16,547,629,234
RMSE: 128,638
R² Score: 0.782


# new value pridiction part

In [ ]:
area = 150
room = 3
parking = 1
warehouse = 1
elevator = 1
address_encoded = 2

In [ ]:
new_data = np.array([[area, room, parking, warehouse, elevator, address_encoded]])

In [ ]:
new_data_scaled = scaler.transform(new_data)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
predicted_price = model_rial.predict(new_data_scaled)
print("Predicted Price:", predicted_price[0] ,"(rial)")

Predicted Price: 8337453333.333332 (rial)


In [ ]:
predicted_price = model_usd.predict(new_data_scaled)
print("Predicted Price:", predicted_price[0] ,"(USD)")

Predicted Price: 274843.1097899997 (USD)
